import turtle

turtle.shape('turtle') 
turtle.forward(25)
turtle.left(50)
turtle.forward(25)
turtle.left(50)
turtle.forward(75)
turtle.right(50)
turtle.forward(30)
turtle.right(70)
turtle.forward(50)
turtle.circle(100)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.circle(120)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.circle(130)
turtle.forward(100)
turtle.left(250)
turtle.forward(100)
turtle.circle(50)
